#!/bin/bash 
#!
#! Sample PBS file
#!
#! Name of job

#PBS -N NoC_SIM
#PBS -o OUT
#PBS -e ERROR

#! Number of nodes (in this case 1 node with 8 CPU cores)
#! The total number of nodes passed to mpirun will be nodes*ppn 
#! Second entry: Total amount of wall-clock time (true time). 
#! 02:00:00 indicates 02 hours

#PBS -l nodes=1:ppn=4,walltime=10:00:00

#! Mail to user if job aborts
#PBS -m a

#! application name
application="java sim.Main"

#! Run options for the application
options="default.cfg"

###############################################################
### You should not have to change anything below this line ####
###############################################################

#! change the working directory (default is home directory)


cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:
echo `cat $PBS_NODEFILE | uniq`

CLASSPATH='./lib/jgrapht-jdk1.6.jar:./lib/jgrapht-jdk1.6.jar:bin/'

numnodes=`wc $PBS_NODEFILE | awk '{ print $1 }'`

export OMP_NUM_THREADS=$numnodes
export CLASSPATH=$CLASSPATH
echo $JUNIT_JAR

#! Run the executable
time $application $options

